CREATE USER 'Monitor' IDENTIFIED BY '1234';

GRANT INSERT, SELECT, UPDATE, DELETE ON c207.alunos TO 'Monitor';

GRANT ALL PRIVILEGES ON c207.* TO 'Professor';

CREATE USER 'Professor' IDENTIFIED BY '4321';

REVOKE INSERT ON c207.alunos FROM 'Monitor';
REVOKE CREATE, DROP ON c207.* FROM 'Professor';

SHOW GRANTS FOR 'Monitor';
SHOW GRANTS FOR 'Professor';