// <auto-generated />
using System;
using FMInvestigacao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMInvestigacao.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220620181201_migracao1")]
    partial class migracao1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FMInvestigacao.Model.Crime", b =>
                {
                    b.Property<int>("IdCrime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCrime"), 1L, 1);

                    b.Property<DateTime?>("Data")
                        .IsRequired()
                        .HasColumnType("DATETIME")
                        .HasColumnName("Data");

                    b.Property<int>("Duracao")
                        .HasColumnType("INT")
                        .HasColumnName("Duracao");

                    b.Property<string>("Local")
                        .HasMaxLength(45)
                        .HasColumnType("VARCHAR(45)")
                        .HasColumnName("Local");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("VARCHAR(45)")
                        .HasColumnName("Nome");

                    b.Property<int?>("VilaoIdVilao")
                        .HasColumnType("int");

                    b.HasKey("IdCrime");

                    b.HasIndex("VilaoIdVilao");

                    b.ToTable("Crime", (string)null);
                });

            modelBuilder.Entity("FMInvestigacao.Model.Vilao", b =>
                {
                    b.Property<int>("IdVilao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVilao"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("VARCHAR(45)")
                        .HasColumnName("Nome");

                    b.Property<int>("NumCrime")
                        .HasColumnType("INT")
                        .HasColumnName("NumCrime");

                    b.HasKey("IdVilao");

                    b.ToTable("Vilao", (string)null);
                });

            modelBuilder.Entity("FMInvestigacao.Model.Crime", b =>
                {
                    b.HasOne("FMInvestigacao.Model.Vilao", "Vilao")
                        .WithMany("Crimes")
                        .HasForeignKey("VilaoIdVilao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Vilao_Crime");

                    b.Navigation("Vilao");
                });

            modelBuilder.Entity("FMInvestigacao.Model.Vilao", b =>
                {
                    b.Navigation("Crimes");
                });
#pragma warning restore 612, 618
        }
    }
}
